// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKlT1ryWV8Q5PXMzxWsBpD4Y9gJnjI8Zw',
    appId: '1:434226759409:web:8de5d07a603d1959eecb50',
    messagingSenderId: '434226759409',
    projectId: 'cloudilya',
    authDomain: 'cloudilya.firebaseapp.com',
    storageBucket: 'cloudilya.appspot.com',
    measurementId: 'G-MYVN05MHXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7a6KWUcRQ6Tht0OO4C56_I4Ep2n5zrZ0',
    appId: '1:434226759409:android:e7d8ed9526b62be7eecb50',
    messagingSenderId: '434226759409',
    projectId: 'cloudilya',
    storageBucket: 'cloudilya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-rFfuhAJBxrACXL0VPcqogNuj_BSyZ00',
    appId: '1:434226759409:ios:57178395f98f7eedeecb50',
    messagingSenderId: '434226759409',
    projectId: 'cloudilya',
    storageBucket: 'cloudilya.appspot.com',
    iosBundleId: 'com.beessoftware.cloudilya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-rFfuhAJBxrACXL0VPcqogNuj_BSyZ00',
    appId: '1:434226759409:ios:ee2436c8c282ac9aeecb50',
    messagingSenderId: '434226759409',
    projectId: 'cloudilya',
    storageBucket: 'cloudilya.appspot.com',
    iosBundleId: 'com.cloudilya.cloudilya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKlT1ryWV8Q5PXMzxWsBpD4Y9gJnjI8Zw',
    appId: '1:434226759409:web:f239d168b6b89dc0eecb50',
    messagingSenderId: '434226759409',
    projectId: 'cloudilya',
    authDomain: 'cloudilya.firebaseapp.com',
    storageBucket: 'cloudilya.appspot.com',
    measurementId: 'G-TD866G5G2P',
  );

}
